Update dotnet.yml
Publishing the test results

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -24,12 +24,17 @@ jobs:
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore
-    # ========= Upload the artifacts ============
-    - run: mkdir -p somepath
-    - uses: actions/upload-artifact@master
-      with:
-        name: my-artifact
-        path: somepath
-    # ===========================================
     - name: Test
-      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
+      #run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
+      run: dotnet test --logger trx --results-directory "TestResults"
+
+    # ========= Upload the artifacts ============
+    - name: Upload dotnet test results
+      uses: actions/upload-artifact@v4
+      with:
+        name: dotnet-test-results
+        path: TestResults
+        # Use always() to always run this step to publish test results when there are test failures
+        if: ${{ always() }}
+    # ===========================================
+
